version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres


  app: # This is the application fin_api
    build: .
    container_name: fin_api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 # You can enter this port too to be able to use the debug
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
